apiVersion: v1
kind: Pod
metadata:
  name: attacker-1
  labels:
    app: krrad-attacker
spec:
  containers:
  - name: attacker
    image: charuka2002/krrad-attacker:v2.0-rc
    imagePullPolicy: IfNotPresent
    securityContext:
      privileged: true
    command: ["sleep", "infinity"]
---
apiVersion: v1
kind: Pod
metadata:
  name: attacker-2
  labels:
    app: krrad-attacker
spec:
  containers:
  - name: attacker
    image: charuka2002/krrad-attacker:v2.0-rc
    imagePullPolicy: IfNotPresent
    securityContext:
      privileged: true
    command: ["sleep", "infinity"]
---
apiVersion: v1
kind: Pod
metadata:
  name: attacker-3
  labels:
    app: krrad-attacker
spec:
  containers:
  - name: attacker
    image: charuka2002/krrad-attacker:v2.0-rc
    imagePullPolicy: IfNotPresent
    securityContext:
      privileged: true
    command: ["sleep", "infinity"]