apiVersion: apps/v1
kind: Deployment
metadata:
  name: krrad-controller
  labels:
    app: krrad-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: krrad-controller
  template:
    metadata:
      labels:
        app: krrad-controller
    spec:
      serviceAccountName: krrad-controller-sa
      containers:
      - name: controller
        image: krrad-controller:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: SENSOR_URL
          value: "http://$(HOST_IP):5000"
        - name: PROMETHEUS_URL
          value: "http://prometheus-service.monitoring.svc.cluster.local:9090"
        ports:
        - containerPort: 8080
