# 1. Create a Service to expose the Controller's metrics
apiVersion: v1
kind: Service
metadata:
  name: krrad-controller-metrics
  labels:
    app: krrad-controller
spec:
  selector:
    app: krrad-controller
  ports:
    - name: metrics
      port: 8000
      targetPort: 8000
      protocol: TCP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: krrad-controller-monitor
  labels:
    release: monitoring 
spec:
  selector:
    matchLabels:
      app: krrad-controller
  endpoints:
    - port: metrics
      interval: 1s
      path: /