apiVersion: v1
kind: Service
metadata:
  name: krrad-controller-metrics
  namespace: default
  labels:
    app: krrad-controller
spec:
  selector:
    app: krrad-controller
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      name: metrics
